# We do not use sudo
sudo: false

# Python versions for matrix
language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6-dev"
  - "nightly"

# Django versions for matrix
env:
  - DJANGO_VERSION='>=1.8,<1.9'
  - DJANGO_VERSION='>=1.9a1,<1.10'
  - DJANGO_VERSION='>=1.10a1,<1.11'

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install python-coveralls
  - pip install Django$DJANGO_VERSION
  - if [[ $TRAVIS_PYTHON_VERSION == '3.2' ]]; then pip install tornado==4.3; fi
  - pip install -r requirements.txt
  - if [[ $TRAVIS_PYTHON_VERSION != '3.2' ]]; then pip install mock --upgrade; fi
  # virtualenv>=14.0.0 has dropped Python 3.2 support
  - travis_retry pip install "virtualenv<14.0.0" "tox>=1.9"
  - if [[ $TRAVIS_PYTHON_VERSION == '3.2' ]]; then travis_retry pip install 'coverage<4.0'; fi
  - travis_retry python setup.py install

# Command to run tests, e.g. python setup.py test
script:
  - export ASYNC_TEST_TIMEOUT=15
  - coverage run manage.py test -v 2 --failfast

# Report to coveralls
after_success:
  - coveralls
  - pylint tornado_websockets

matrix:
  exclude:
    - python: "3.2"
      env: DJANGO_VERSION='>=1.9a1,<1.10'
    - python: "3.2"
      env: DJANGO_VERSION='>=1.10a1,<1.11'
    - python: "3.3"
      env: DJANGO_VERSION='>=1.9a1,<1.10'
    - python: "3.3"
      env: DJANGO_VERSION='>=1.10a1,<1.11'
